name: Discord Webhook

on:
  schedule:
    - cron: "30 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Jakarta

      - name: Running Script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          pip install -r requirements.txt
          python script_remote.py
